<?php

/**
 * Class ItemCustom
 */

class ItemCustom extends Item
{
    public function attributeLabels()
    {
        return array(
            'item_code' => 'Kode Barcode',
            'cat_code' => 'Kelompok',
            'price' => 'Harga',
            'qty_stock' => 'Stok'
        );
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    /**
     * @param string $className
     * @return ItemCustom
     */
    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function search()
    {
        return parent::search(); // TODO: Change the autogenerated stub
    }
}