<?php


class StoresItemCustom extends StoresItem
{
    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public function search()
    {
        return parent::search(); // TODO: Change the autogenerated stub
    }

    public static function isSelling($store_id, $item_id) {
        $model = self::model()->findByAttributes(array(
            'item_id'=> $item_id,
            'store_id'=>$store_id
        ));
        return !empty($model);
    }
}