<?php
/**
 * Created by PhpStorm.
 * User: purwaren
 * Date: 12/26/18
 * Time: 12:12 AM
 */

class SuppliersCustom extends Suppliers
{
    public function rules()
    {
        return parent::rules(); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return array(
            'id' => 'ID',
            'code' => 'Kode',
            'name' => 'Nama',
            'address' => 'Alamat',
            'phone' => 'Telepon',
            'type' => 'Tipe',
            'created_by' => 'Dibuat Oleh',
            'created_at' => 'Dibuat Pada',
        );
    }

    public static function model($className = __CLASS__)
    {
        return parent::model($className); // TODO: Change the autogenerated stub
    }

    public static function getAllSupplierOptions() {
        $criteria = new CDbCriteria();
        $criteria->order = 'code';

        $models = self::model()->findAll($criteria);
        $options = array();

        foreach ($models as $model) {
            $options[$model->id] = $model->code.' ('.strtoupper($model->name).')';
        }

        return $options;
    }
}